name: 💡 Feature Request
title: '[FEATURE REQUEST] Feature'
description: Request a feature with the API
labels: 'feature request'
body:

- type: input
  id: request
  attributes:
    label: Feature requested
    description: "The feature you're requesting. Should have to do with the API."
    placeholder: "Add this endpoint because..."
  validations:
    required: true
