name: 🚀 Suggest an Icon
title: '[NEW ICON] Icon name'
description: Suggest an icon to be added to the list!
labels: 'icon suggestion'
body:

- type: input
  id: icon-name
  attributes:
    label: Icon Name
    description: "The name of the icon you're suggesting. Feel free to suggest more than one!"
    placeholder: "Github"
  validations:
    required: true

# reason to add block
- type: textarea
  id: reason
  attributes:
    label: Why?
    description: "Why we should add the icon(s) to the project."
    placeholder: "It's popular for something..."
  validations:
    required: true

# reference image block
- type: textarea
  id: reference-image
  attributes:
    label: Reference Image
    description: "Do you have any images of what the logo looks like? SVG preferred."
    placeholder: "Feel free to drag and drop the files here."
  validations:
    required: false
